version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - nuget
    groups:
      dotnet-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      dotnet-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    groups:
      container-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      container-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
